#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Shamely.Resource", IsApplication=true)]

namespace Shamely
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.alliance.calendar.Resource.Animation.cal_fade_in = global::Shamely.Resource.Animation.cal_fade_in;
			global::com.alliance.calendar.Resource.Animation.cal_slide_down = global::Shamely.Resource.Animation.cal_slide_down;
			global::com.alliance.calendar.Resource.Animation.cal_slide_up = global::Shamely.Resource.Animation.cal_slide_up;
			global::com.alliance.calendar.Resource.Attribute.calendar_background = global::Shamely.Resource.Attribute.calendar_background;
			global::com.alliance.calendar.Resource.Attribute.calendar_cellbackground = global::Shamely.Resource.Attribute.calendar_cellbackground;
			global::com.alliance.calendar.Resource.Attribute.calendar_highlight_cellbackground = global::Shamely.Resource.Attribute.calendar_highlight_cellbackground;
			global::com.alliance.calendar.Resource.Attribute.calendar_next_text = global::Shamely.Resource.Attribute.calendar_next_text;
			global::com.alliance.calendar.Resource.Attribute.calendar_nextbutton_background = global::Shamely.Resource.Attribute.calendar_nextbutton_background;
			global::com.alliance.calendar.Resource.Attribute.calendar_prev_text = global::Shamely.Resource.Attribute.calendar_prev_text;
			global::com.alliance.calendar.Resource.Attribute.calendar_prevbutton_background = global::Shamely.Resource.Attribute.calendar_prevbutton_background;
			global::com.alliance.calendar.Resource.Attribute.calendar_separator = global::Shamely.Resource.Attribute.calendar_separator;
			global::com.alliance.calendar.Resource.Attribute.calendar_shownextmonthsfromcurrentmonth = global::Shamely.Resource.Attribute.calendar_shownextmonthsfromcurrentmonth;
			global::com.alliance.calendar.Resource.Attribute.calendar_showonlycurrentmonth = global::Shamely.Resource.Attribute.calendar_showonlycurrentmonth;
			global::com.alliance.calendar.Resource.Attribute.calendar_showprevmonthsfromcurrentmonth = global::Shamely.Resource.Attribute.calendar_showprevmonthsfromcurrentmonth;
			global::com.alliance.calendar.Resource.Attribute.calendar_weekstartswith = global::Shamely.Resource.Attribute.calendar_weekstartswith;
			global::com.alliance.calendar.Resource.Color.black = global::Shamely.Resource.Color.black;
			global::com.alliance.calendar.Resource.Color.daycell_default_bottom = global::Shamely.Resource.Color.daycell_default_bottom;
			global::com.alliance.calendar.Resource.Color.daycell_default_middle = global::Shamely.Resource.Color.daycell_default_middle;
			global::com.alliance.calendar.Resource.Color.daycell_default_top = global::Shamely.Resource.Color.daycell_default_top;
			global::com.alliance.calendar.Resource.Color.daycell_dim_bottom = global::Shamely.Resource.Color.daycell_dim_bottom;
			global::com.alliance.calendar.Resource.Color.daycell_dim_middle = global::Shamely.Resource.Color.daycell_dim_middle;
			global::com.alliance.calendar.Resource.Color.daycell_dim_top = global::Shamely.Resource.Color.daycell_dim_top;
			global::com.alliance.calendar.Resource.Color.daycell_highlight_bottom = global::Shamely.Resource.Color.daycell_highlight_bottom;
			global::com.alliance.calendar.Resource.Color.daycell_highlight_middle = global::Shamely.Resource.Color.daycell_highlight_middle;
			global::com.alliance.calendar.Resource.Color.daycell_highlight_top = global::Shamely.Resource.Color.daycell_highlight_top;
			global::com.alliance.calendar.Resource.Color.daycell_selected_bottom = global::Shamely.Resource.Color.daycell_selected_bottom;
			global::com.alliance.calendar.Resource.Color.daycell_selected_middle = global::Shamely.Resource.Color.daycell_selected_middle;
			global::com.alliance.calendar.Resource.Color.daycell_selected_top = global::Shamely.Resource.Color.daycell_selected_top;
			global::com.alliance.calendar.Resource.Color.daynamecell_default_bottom = global::Shamely.Resource.Color.daynamecell_default_bottom;
			global::com.alliance.calendar.Resource.Color.daynamecell_default_middle = global::Shamely.Resource.Color.daynamecell_default_middle;
			global::com.alliance.calendar.Resource.Color.daynamecell_default_top = global::Shamely.Resource.Color.daynamecell_default_top;
			global::com.alliance.calendar.Resource.Color.white = global::Shamely.Resource.Color.white;
			global::com.alliance.calendar.Resource.Drawable.daynamecell_drawable = global::Shamely.Resource.Drawable.daynamecell_drawable;
			global::com.alliance.calendar.Resource.Drawable.default_cell_selector = global::Shamely.Resource.Drawable.default_cell_selector;
			global::com.alliance.calendar.Resource.Drawable.default_dim_selector = global::Shamely.Resource.Drawable.default_dim_selector;
			global::com.alliance.calendar.Resource.Drawable.default_highlight_selector = global::Shamely.Resource.Drawable.default_highlight_selector;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_Gridview_Days = global::Shamely.Resource.Id.Alliance_Calendar_Gridview_Days;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_GridviewdayNames = global::Shamely.Resource.Id.Alliance_Calendar_GridviewdayNames;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_Num_Day = global::Shamely.Resource.Id.Alliance_Calendar_Num_Day;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_btnNext = global::Shamely.Resource.Id.Alliance_Calendar_btnNext;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_btnPrev = global::Shamely.Resource.Id.Alliance_Calendar_btnPrev;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_txtYearMonth = global::Shamely.Resource.Id.Alliance_Calendar_txtYearMonth;
			global::com.alliance.calendar.Resource.Id.monday = global::Shamely.Resource.Id.monday;
			global::com.alliance.calendar.Resource.Id.sunday = global::Shamely.Resource.Id.sunday;
			global::com.alliance.calendar.Resource.Layout.Alliance_Calendar_Main = global::Shamely.Resource.Layout.Alliance_Calendar_Main;
			global::com.alliance.calendar.Resource.Layout.day_gridcell = global::Shamely.Resource.Layout.day_gridcell;
			global::com.alliance.calendar.Resource.String.ApplicationName = global::Shamely.Resource.String.ApplicationName;
			global::com.alliance.calendar.Resource.String.Hello = global::Shamely.Resource.String.Hello;
			global::com.alliance.calendar.Resource.Style.calendar_default_cell_text = global::Shamely.Resource.Style.calendar_default_cell_text;
			global::com.alliance.calendar.Resource.Style.calendar_default_highlight_text = global::Shamely.Resource.Style.calendar_default_highlight_text;
			global::com.alliance.calendar.Resource.Style.calendar_default_weekend_text = global::Shamely.Resource.Style.calendar_default_weekend_text;
			global::com.alliance.calendar.Resource.Styleable.calendarthis = global::Shamely.Resource.Styleable.calendarthis;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_background = global::Shamely.Resource.Styleable.calendarthis_calendar_background;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_cellbackground = global::Shamely.Resource.Styleable.calendarthis_calendar_cellbackground;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_highlight_cellbackground = global::Shamely.Resource.Styleable.calendarthis_calendar_highlight_cellbackground;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_next_text = global::Shamely.Resource.Styleable.calendarthis_calendar_next_text;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_nextbutton_background = global::Shamely.Resource.Styleable.calendarthis_calendar_nextbutton_background;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_prev_text = global::Shamely.Resource.Styleable.calendarthis_calendar_prev_text;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_prevbutton_background = global::Shamely.Resource.Styleable.calendarthis_calendar_prevbutton_background;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_separator = global::Shamely.Resource.Styleable.calendarthis_calendar_separator;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_shownextmonthsfromcurrentmonth = global::Shamely.Resource.Styleable.calendarthis_calendar_shownextmonthsfromcurrentmonth;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_showonlycurrentmonth = global::Shamely.Resource.Styleable.calendarthis_calendar_showonlycurrentmonth;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_showprevmonthsfromcurrentmonth = global::Shamely.Resource.Styleable.calendarthis_calendar_showprevmonthsfromcurrentmonth;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_weekstartswith = global::Shamely.Resource.Styleable.calendarthis_calendar_weekstartswith;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int cal_fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cal_slide_down = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cal_slide_up = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int calendar_background = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int calendar_cellbackground = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int calendar_highlight_cellbackground = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int calendar_next_text = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int calendar_nextbutton_background = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int calendar_prev_text = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int calendar_prevbutton_background = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int calendar_separator = 2130771968;
			
			// aapt resource value: 0x7f01000b
			public const int calendar_shownextmonthsfromcurrentmonth = 2130771979;
			
			// aapt resource value: 0x7f010009
			public const int calendar_showonlycurrentmonth = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int calendar_showprevmonthsfromcurrentmonth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int calendar_weekstartswith = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int black = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int daycell_default_bottom = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int daycell_default_middle = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int daycell_default_top = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int daycell_dim_bottom = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int daycell_dim_middle = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int daycell_dim_top = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int daycell_highlight_bottom = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int daycell_highlight_middle = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int daycell_highlight_top = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int daycell_selected_bottom = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int daycell_selected_middle = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int daycell_selected_top = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int daynamecell_default_bottom = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int daynamecell_default_middle = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int daynamecell_default_top = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int daynamecell_drawable = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int default_cell_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int default_dim_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int default_highlight_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000d
			public const int AddFoodButton = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int Alliance_Calendar_Gridview_Days = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int Alliance_Calendar_GridviewdayNames = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int Alliance_Calendar_Num_Day = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int Alliance_Calendar_btnNext = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int Alliance_Calendar_btnPrev = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int Alliance_Calendar_txtYearMonth = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int button1 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int button2 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int button3 = 2131230725;
			
			// aapt resource value: 0x7f08000c
			public const int linearLayout1 = 2131230732;
			
			// aapt resource value: 0x7f080000
			public const int monday = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int sunday = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int textView1 = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddFood = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Alliance_Calendar_Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int day_gridcell = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int app_name = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int hello = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int calendar_default_cell_text = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int calendar_default_highlight_text = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int calendar_default_weekend_text = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] calendarthis = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int calendarthis_calendar_background = 1;
			
			// aapt resource value: 2
			public const int calendarthis_calendar_cellbackground = 2;
			
			// aapt resource value: 3
			public const int calendarthis_calendar_highlight_cellbackground = 3;
			
			// aapt resource value: 6
			public const int calendarthis_calendar_next_text = 6;
			
			// aapt resource value: 5
			public const int calendarthis_calendar_nextbutton_background = 5;
			
			// aapt resource value: 7
			public const int calendarthis_calendar_prev_text = 7;
			
			// aapt resource value: 4
			public const int calendarthis_calendar_prevbutton_background = 4;
			
			// aapt resource value: 0
			public const int calendarthis_calendar_separator = 0;
			
			// aapt resource value: 11
			public const int calendarthis_calendar_shownextmonthsfromcurrentmonth = 11;
			
			// aapt resource value: 9
			public const int calendarthis_calendar_showonlycurrentmonth = 9;
			
			// aapt resource value: 10
			public const int calendarthis_calendar_showprevmonthsfromcurrentmonth = 10;
			
			// aapt resource value: 8
			public const int calendarthis_calendar_weekstartswith = 8;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
